// This is great for checking out your billable ingest patterns over the past quarter for QBRs etc. 


Usage                                                                               // <--Query the ***Usage*** table
| where TimeGenerated > ago(90d)                                                    // <--Query the last 90 days
| where IsBillable == true                                                          // <--Only include 'billable' date
| summarize TotalVolumeGB = sum(Quantity) / 1000 by bin(StartTime, 1d), Solution    // <--Chop it up into GB / Day
| render columnchart                                                                // <--Graph the results