name: Update README Tree on PR

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  readme-tree:
    uses: Coalfire-CF/Actions/.github/workflows/org-tree-readme.yml@f68c1a32bfe64aefd9cbcb1db1f0f40339340eda # v0.12.1
    with:
      commit_message: "chore: update README tree"
      exclude_pattern: ".git|node_modules|.github|dist|build"
      working_directory: "."
