name: Org Release
on:
    pull_request:
        types:
        - closed
        branches:
        - [ $default-branch]

jobs:
  my-job:
    uses: Coalfire-CF/.github/.github/workflows/org-release.yml@main